import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const registryPath = path.join(__dirname, '../data/examRegistry.json');

const existingRegistry = JSON.parse(fs.readFileSync(registryPath, 'utf8'));

// Fix any missing fields in existing registry
existingRegistry.forEach(e => {
  if (!e.adapter_type) e.adapter_type = 'generic';
  if (e.active === undefined) e.active = 1;
  if (!e.scrape_frequency) e.scrape_frequency = 360;
  if (!e.frequency) e.frequency = 'annual';
  if (e.state === undefined) e.state = null;
});

const existingNames = new Set(existingRegistry.map(e => (e.short_name || e.name).toLowerCase().trim()));

const newExams = [
  // ==========================================
  // KARNATAKA - SMALL TO HIGH (Group D to Gazetted)
  // ==========================================
  // High / Gazetted / Officers
  {
    name: "Karnataka Judicial Service - Civil Judge Examination",
    short_name: "Karnataka Civil Judge",
    conducting_body: "High Court of Karnataka",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://karnatakajudiciary.kar.nic.in",
    careers_url: "https://karnatakajudiciary.kar.nic.in/recruitment.php",
    notification_url: "https://karnatakajudiciary.kar.nic.in/recruitment.php",
    results_url: "https://karnatakajudiciary.kar.nic.in/results.php",
    admit_card_url: "https://karnatakajudiciary.kar.nic.in",
    syllabus_source_url: "https://karnatakajudiciary.kar.nic.in",
    frequency: "annual",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "KPSC Assistant Conservator of Forests (ACF Group A)",
    short_name: "KPSC ACF",
    conducting_body: "Karnataka Public Service Commission",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://kpsc.kar.nic.in",
    careers_url: "https://kpsc.kar.nic.in/notifications",
    notification_url: "https://kpsc.kar.nic.in/notifications",
    results_url: "https://kpsc.kar.nic.in/results",
    admit_card_url: "https://kpsc.kar.nic.in",
    syllabus_source_url: "https://kpsc.kar.nic.in",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "kpsc",
    active: 1
  },
  {
    name: "KPSC Range Forest Officer (RFO Group B)",
    short_name: "KPSC RFO",
    conducting_body: "Karnataka Public Service Commission",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://kpsc.kar.nic.in",
    careers_url: "https://kpsc.kar.nic.in/notifications",
    notification_url: "https://kpsc.kar.nic.in/notifications",
    results_url: "https://kpsc.kar.nic.in/results",
    admit_card_url: "https://kpsc.kar.nic.in",
    syllabus_source_url: "https://kpsc.kar.nic.in",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "kpsc",
    active: 1
  },
  {
    name: "KPSC Motor Vehicle Inspector (MVI / Transport Department)",
    short_name: "KPSC MVI",
    conducting_body: "Karnataka Public Service Commission",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://kpsc.kar.nic.in",
    careers_url: "https://kpsc.kar.nic.in/notifications",
    notification_url: "https://kpsc.kar.nic.in/notifications",
    results_url: "https://kpsc.kar.nic.in/results",
    admit_card_url: "https://kpsc.kar.nic.in",
    syllabus_source_url: "https://kpsc.kar.nic.in",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "kpsc",
    active: 1
  },
  {
    name: "KPSC Commercial Tax Inspector (CTI Group C Non-Technical)",
    short_name: "KPSC CTI",
    conducting_body: "Karnataka Public Service Commission",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://kpsc.kar.nic.in",
    careers_url: "https://kpsc.kar.nic.in/notifications",
    notification_url: "https://kpsc.kar.nic.in/notifications",
    results_url: "https://kpsc.kar.nic.in/results",
    admit_card_url: "https://kpsc.kar.nic.in",
    syllabus_source_url: "https://kpsc.kar.nic.in",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "kpsc",
    active: 1
  },
  {
    name: "KEA Assistant Professor Recruitment (Collegiate Education)",
    short_name: "KEA Asst Professor",
    conducting_body: "Karnataka Examinations Authority",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://cetonline.karnataka.gov.in/kea",
    careers_url: "https://cetonline.karnataka.gov.in/kea/recruitment",
    notification_url: "https://cetonline.karnataka.gov.in/kea/recruitment",
    results_url: "https://cetonline.karnataka.gov.in/kea/results",
    admit_card_url: "https://cetonline.karnataka.gov.in/kea",
    syllabus_source_url: "https://cetonline.karnataka.gov.in/kea",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "kea",
    active: 1
  },
  {
    name: "KEA Pre-University College Lecturer Recruitment",
    short_name: "KEA PU Lecturer",
    conducting_body: "Karnataka Examinations Authority",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://cetonline.karnataka.gov.in/kea",
    careers_url: "https://cetonline.karnataka.gov.in/kea/recruitment",
    notification_url: "https://cetonline.karnataka.gov.in/kea/recruitment",
    results_url: "https://cetonline.karnataka.gov.in/kea/results",
    admit_card_url: "https://cetonline.karnataka.gov.in/kea",
    syllabus_source_url: "https://cetonline.karnataka.gov.in/kea",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "kea",
    active: 1
  },
  {
    name: "Karnataka Public Works Department Assistant Engineer (PWD AE Civil/Mechanical)",
    short_name: "Karnataka PWD AE",
    conducting_body: "Karnataka PWD / KPSC",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://kpsc.kar.nic.in",
    careers_url: "https://kpsc.kar.nic.in/notifications",
    notification_url: "https://kpsc.kar.nic.in/notifications",
    results_url: "https://kpsc.kar.nic.in/results",
    admit_card_url: "https://kpsc.kar.nic.in",
    syllabus_source_url: "https://kpsc.kar.nic.in",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "Karnataka Water Resources Department Assistant Engineer (WRD AE Irrigation)",
    short_name: "Karnataka WRD AE",
    conducting_body: "Water Resources Department / KPSC",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://waterresources.karnataka.gov.in",
    careers_url: "https://kpsc.kar.nic.in",
    notification_url: "https://kpsc.kar.nic.in",
    results_url: "https://kpsc.kar.nic.in",
    admit_card_url: "https://kpsc.kar.nic.in",
    syllabus_source_url: "https://kpsc.kar.nic.in",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  // Karnataka Rural Development & Panchayat Raj (RDPR) - PDO, GPS, SDAA
  {
    name: "KEA Panchayat Development Officer (PDO)",
    short_name: "KEA PDO",
    conducting_body: "Karnataka Examinations Authority",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://cetonline.karnataka.gov.in/kea",
    careers_url: "https://cetonline.karnataka.gov.in/kea/recruitment",
    notification_url: "https://cetonline.karnataka.gov.in/kea/recruitment",
    results_url: "https://cetonline.karnataka.gov.in/kea/results",
    admit_card_url: "https://cetonline.karnataka.gov.in/kea",
    syllabus_source_url: "https://cetonline.karnataka.gov.in/kea",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "kea",
    active: 1
  },
  {
    name: "KEA Grama Panchayat Secretary Grade-1 (GPS-1)",
    short_name: "KEA GPS Grade-1",
    conducting_body: "Karnataka Examinations Authority",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://cetonline.karnataka.gov.in/kea",
    careers_url: "https://cetonline.karnataka.gov.in/kea/recruitment",
    notification_url: "https://cetonline.karnataka.gov.in/kea/recruitment",
    results_url: "https://cetonline.karnataka.gov.in/kea/results",
    admit_card_url: "https://cetonline.karnataka.gov.in/kea",
    syllabus_source_url: "https://cetonline.karnataka.gov.in/kea",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "kea",
    active: 1
  },
  {
    name: "KEA Grama Panchayat Secretary Grade-2 (GPS-2)",
    short_name: "KEA GPS Grade-2",
    conducting_body: "Karnataka Examinations Authority",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://cetonline.karnataka.gov.in/kea",
    careers_url: "https://cetonline.karnataka.gov.in/kea/recruitment",
    notification_url: "https://cetonline.karnataka.gov.in/kea/recruitment",
    results_url: "https://cetonline.karnataka.gov.in/kea/results",
    admit_card_url: "https://cetonline.karnataka.gov.in/kea",
    syllabus_source_url: "https://cetonline.karnataka.gov.in/kea",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "kea",
    active: 1
  },
  {
    name: "KEA Rural Development Second Division Accounts Assistant (SDAA)",
    short_name: "KEA SDAA",
    conducting_body: "Karnataka Examinations Authority",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://cetonline.karnataka.gov.in/kea",
    careers_url: "https://cetonline.karnataka.gov.in/kea/recruitment",
    notification_url: "https://cetonline.karnataka.gov.in/kea/recruitment",
    results_url: "https://cetonline.karnataka.gov.in/kea/results",
    admit_card_url: "https://cetonline.karnataka.gov.in/kea",
    syllabus_source_url: "https://cetonline.karnataka.gov.in/kea",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "kea",
    active: 1
  },
  // Police & Uniformed Forces in Karnataka (Sub-Inspector to Constable to Warder)
  {
    name: "Karnataka State Police Armed Reserve Sub-Inspector (CAR / DAR RSI)",
    short_name: "KSP Armed RSI",
    conducting_body: "Karnataka State Police",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://ksp-recruitment.in",
    careers_url: "https://ksp-recruitment.in",
    notification_url: "https://ksp-recruitment.in",
    results_url: "https://ksp-recruitment.in",
    admit_card_url: "https://ksp-recruitment.in",
    syllabus_source_url: "https://ksp.karnataka.gov.in",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "Karnataka State Police Wireless Sub-Inspector & Technician",
    short_name: "KSP Wireless SI",
    conducting_body: "Karnataka State Police",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://ksp-recruitment.in",
    careers_url: "https://ksp-recruitment.in",
    notification_url: "https://ksp-recruitment.in",
    results_url: "https://ksp-recruitment.in",
    admit_card_url: "https://ksp-recruitment.in",
    syllabus_source_url: "https://ksp.karnataka.gov.in",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "Karnataka State Industrial Security Force Sub-Inspector (KSISF PSI)",
    short_name: "KSP KSISF PSI",
    conducting_body: "Karnataka State Police",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://ksp-recruitment.in",
    careers_url: "https://ksp-recruitment.in",
    notification_url: "https://ksp-recruitment.in",
    results_url: "https://ksp-recruitment.in",
    admit_card_url: "https://ksp-recruitment.in",
    syllabus_source_url: "https://ksp.karnataka.gov.in",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "Karnataka Prisons Department Jailor (Group B / C)",
    short_name: "Karnataka Jailor",
    conducting_body: "Karnataka Prisons and Correctional Services",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://prisons.karnataka.gov.in",
    careers_url: "https://ksp-recruitment.in",
    notification_url: "https://ksp-recruitment.in",
    results_url: "https://ksp-recruitment.in",
    admit_card_url: "https://ksp-recruitment.in",
    syllabus_source_url: "https://prisons.karnataka.gov.in",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "Karnataka State Police Armed Police Constable (CAR / DAR Constable)",
    short_name: "KSP Armed PC",
    conducting_body: "Karnataka State Police",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://ksp-recruitment.in",
    careers_url: "https://ksp-recruitment.in",
    notification_url: "https://ksp-recruitment.in",
    results_url: "https://ksp-recruitment.in",
    admit_card_url: "https://ksp-recruitment.in",
    syllabus_source_url: "https://ksp.karnataka.gov.in",
    frequency: "annual",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "Karnataka State Industrial Security Force Constable (KSISF Constable)",
    short_name: "KSP KSISF PC",
    conducting_body: "Karnataka State Police",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://ksp-recruitment.in",
    careers_url: "https://ksp-recruitment.in",
    notification_url: "https://ksp-recruitment.in",
    results_url: "https://ksp-recruitment.in",
    admit_card_url: "https://ksp-recruitment.in",
    syllabus_source_url: "https://ksp.karnataka.gov.in",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "Karnataka Prisons Department Warder (Male & Female)",
    short_name: "Karnataka Warder",
    conducting_body: "Karnataka Prisons and Correctional Services",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://prisons.karnataka.gov.in",
    careers_url: "https://ksp-recruitment.in",
    notification_url: "https://ksp-recruitment.in",
    results_url: "https://ksp-recruitment.in",
    admit_card_url: "https://ksp-recruitment.in",
    syllabus_source_url: "https://prisons.karnataka.gov.in",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  // Karnataka Forest & Excise
  {
    name: "Karnataka Forest Department Deputy Range Forest Officer (DRFO)",
    short_name: "Karnataka DRFO",
    conducting_body: "Karnataka Forest Department",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://aranya.gov.in",
    careers_url: "https://aranya.gov.in",
    notification_url: "https://aranya.gov.in",
    results_url: "https://aranya.gov.in",
    admit_card_url: "https://aranya.gov.in",
    syllabus_source_url: "https://aranya.gov.in",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "Karnataka Forest Department Forest Watcher (Group D)",
    short_name: "Karnataka Forest Watcher",
    conducting_body: "Karnataka Forest Department",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://aranya.gov.in",
    careers_url: "https://aranya.gov.in",
    notification_url: "https://aranya.gov.in",
    results_url: "https://aranya.gov.in",
    admit_card_url: "https://aranya.gov.in",
    syllabus_source_url: "https://aranya.gov.in",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "Karnataka Excise Department Sub-Inspector (ESI)",
    short_name: "Karnataka Excise SI",
    conducting_body: "Karnataka Excise Department / KPSC",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://stateexcise.karnataka.gov.in",
    careers_url: "https://kpsc.kar.nic.in",
    notification_url: "https://kpsc.kar.nic.in",
    results_url: "https://kpsc.kar.nic.in",
    admit_card_url: "https://kpsc.kar.nic.in",
    syllabus_source_url: "https://kpsc.kar.nic.in",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "Karnataka Excise Department Excise Guard (EG)",
    short_name: "Karnataka Excise Guard",
    conducting_body: "Karnataka Excise Department / KEA",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://stateexcise.karnataka.gov.in",
    careers_url: "https://cetonline.karnataka.gov.in/kea",
    notification_url: "https://cetonline.karnataka.gov.in/kea",
    results_url: "https://cetonline.karnataka.gov.in/kea",
    admit_card_url: "https://cetonline.karnataka.gov.in/kea",
    syllabus_source_url: "https://stateexcise.karnataka.gov.in",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  // Karnataka ESCOMs & Power (HESCOM, GESCOM, CESC, MESCOM, KPCL) - Lineman, JE, AE
  {
    name: "HESCOM Hubli - Assistant Engineer, Junior Engineer & Lineman",
    short_name: "HESCOM Recruitment",
    conducting_body: "Hubli Electricity Supply Company Limited",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://hescom.karnataka.gov.in",
    careers_url: "https://hescom.karnataka.gov.in/recruitment",
    notification_url: "https://hescom.karnataka.gov.in/recruitment",
    results_url: "https://hescom.karnataka.gov.in",
    admit_card_url: "https://hescom.karnataka.gov.in",
    syllabus_source_url: "https://hescom.karnataka.gov.in",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "GESCOM Kalaburagi - AE, JE, Junior Assistant & Lineman",
    short_name: "GESCOM Recruitment",
    conducting_body: "Gulbarga Electricity Supply Company Limited",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://gescom.karnataka.gov.in",
    careers_url: "https://gescom.karnataka.gov.in/recruitment",
    notification_url: "https://gescom.karnataka.gov.in/recruitment",
    results_url: "https://gescom.karnataka.gov.in",
    admit_card_url: "https://gescom.karnataka.gov.in",
    syllabus_source_url: "https://gescom.karnataka.gov.in",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "CESC Mysuru - AE, JE, Lineman & Station Attendant",
    short_name: "CESC Mysuru Recruitment",
    conducting_body: "Chamundeshwari Electricity Supply Corporation",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://cescmysore.karnataka.gov.in",
    careers_url: "https://cescmysore.karnataka.gov.in",
    notification_url: "https://cescmysore.karnataka.gov.in",
    results_url: "https://cescmysore.karnataka.gov.in",
    admit_card_url: "https://cescmysore.karnataka.gov.in",
    syllabus_source_url: "https://cescmysore.karnataka.gov.in",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "MESCOM Mangaluru - AE, JE, Lineman & Junior Assistant",
    short_name: "MESCOM Recruitment",
    conducting_body: "Mangalore Electricity Supply Company Limited",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://mescom.karnataka.gov.in",
    careers_url: "https://mescom.karnataka.gov.in",
    notification_url: "https://mescom.karnataka.gov.in",
    results_url: "https://mescom.karnataka.gov.in",
    admit_card_url: "https://mescom.karnataka.gov.in",
    syllabus_source_url: "https://mescom.karnataka.gov.in",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "KPCL Karnataka Power Corporation Limited (AE / JE / Chemist)",
    short_name: "KPCL Recruitment",
    conducting_body: "Karnataka Power Corporation Limited",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://karnatakapower.com",
    careers_url: "https://karnatakapower.com/recruitment",
    notification_url: "https://karnatakapower.com",
    results_url: "https://karnatakapower.com",
    admit_card_url: "https://karnatakapower.com",
    syllabus_source_url: "https://karnatakapower.com",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "KPTCL Junior Lineman (JLM) & Junior Station Attendant (JSA - Group D)",
    short_name: "KPTCL JLM / JSA",
    conducting_body: "Karnataka Power Transmission Corporation Limited",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://kptcl.karnataka.gov.in",
    careers_url: "https://kptcl.karnataka.gov.in",
    notification_url: "https://kptcl.karnataka.gov.in",
    results_url: "https://kptcl.karnataka.gov.in",
    admit_card_url: "https://kptcl.karnataka.gov.in",
    syllabus_source_url: "https://kptcl.karnataka.gov.in",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  // Karnataka Transport Corporations (Drivers, Conductors, Mechanics)
  {
    name: "KSRTC Driver & Driver-cum-Conductor Recruitment",
    short_name: "KSRTC Driver",
    conducting_body: "Karnataka State Road Transport Corporation",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://ksrtc.karnataka.gov.in",
    careers_url: "https://ksrtc.karnataka.gov.in/recruitment",
    notification_url: "https://ksrtc.karnataka.gov.in",
    results_url: "https://ksrtc.karnataka.gov.in",
    admit_card_url: "https://ksrtc.karnataka.gov.in",
    syllabus_source_url: "https://ksrtc.karnataka.gov.in",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "BMTC Bengaluru Driver & Conductor Recruitment",
    short_name: "BMTC Driver/Conductor",
    conducting_body: "Bangalore Metropolitan Transport Corporation",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://mybmtc.karnataka.gov.in",
    careers_url: "https://mybmtc.karnataka.gov.in",
    notification_url: "https://mybmtc.karnataka.gov.in",
    results_url: "https://mybmtc.karnataka.gov.in",
    admit_card_url: "https://mybmtc.karnataka.gov.in",
    syllabus_source_url: "https://mybmtc.karnataka.gov.in",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "NWKRTC Hubballi Driver & Technical Assistant Recruitment",
    short_name: "NWKRTC Recruitment",
    conducting_body: "North Western Karnataka Road Transport Corporation",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://nwkrtc.karnataka.gov.in",
    careers_url: "https://nwkrtc.karnataka.gov.in",
    notification_url: "https://nwkrtc.karnataka.gov.in",
    results_url: "https://nwkrtc.karnataka.gov.in",
    admit_card_url: "https://nwkrtc.karnataka.gov.in",
    syllabus_source_url: "https://nwkrtc.karnataka.gov.in",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "KKRTC Kalaburagi Driver & Conductor Recruitment",
    short_name: "KKRTC Recruitment",
    conducting_body: "Kalyana Karnataka Road Transport Corporation",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://kkrtc.karnataka.gov.in",
    careers_url: "https://kkrtc.karnataka.gov.in",
    notification_url: "https://kkrtc.karnataka.gov.in",
    results_url: "https://kkrtc.karnataka.gov.in",
    admit_card_url: "https://kkrtc.karnataka.gov.in",
    syllabus_source_url: "https://kkrtc.karnataka.gov.in",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  // Karnataka High Court & District Courts Group D, Typists, Peons
  {
    name: "Karnataka High Court Typist, Copyist & Stenographer",
    short_name: "Karnataka HC Typist",
    conducting_body: "High Court of Karnataka",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://karnatakajudiciary.kar.nic.in",
    careers_url: "https://karnatakajudiciary.kar.nic.in/recruitment.php",
    notification_url: "https://karnatakajudiciary.kar.nic.in/recruitment.php",
    results_url: "https://karnatakajudiciary.kar.nic.in",
    admit_card_url: "https://karnatakajudiciary.kar.nic.in",
    syllabus_source_url: "https://karnatakajudiciary.kar.nic.in",
    frequency: "annual",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "Karnataka High Court Peon, Watchman & Sweeper (Group D)",
    short_name: "Karnataka HC Peon (Group D)",
    conducting_body: "High Court of Karnataka",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://karnatakajudiciary.kar.nic.in",
    careers_url: "https://karnatakajudiciary.kar.nic.in/recruitment.php",
    notification_url: "https://karnatakajudiciary.kar.nic.in/recruitment.php",
    results_url: "https://karnatakajudiciary.kar.nic.in",
    admit_card_url: "https://karnatakajudiciary.kar.nic.in",
    syllabus_source_url: "https://karnatakajudiciary.kar.nic.in",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "Karnataka District Courts Peon & Process Server (Group D)",
    short_name: "District Courts Peon",
    conducting_body: "Karnataka Judicial Service / District Courts",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://districts.ecourts.gov.in/karnataka",
    careers_url: "https://districts.ecourts.gov.in/karnataka",
    notification_url: "https://districts.ecourts.gov.in/karnataka",
    results_url: "https://districts.ecourts.gov.in/karnataka",
    admit_card_url: "https://districts.ecourts.gov.in/karnataka",
    syllabus_source_url: "https://districts.ecourts.gov.in/karnataka",
    frequency: "annual",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  // Karnataka Municipal, Health & Anganwadi
  {
    name: "BBMP Bruhat Bengaluru Mahanagara Palike Health Inspector & Junior Engineer",
    short_name: "BBMP Recruitment",
    conducting_body: "BBMP / KEA",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://bbmp.karnataka.gov.in",
    careers_url: "https://cetonline.karnataka.gov.in/kea",
    notification_url: "https://bbmp.karnataka.gov.in",
    results_url: "https://bbmp.karnataka.gov.in",
    admit_card_url: "https://cetonline.karnataka.gov.in/kea",
    syllabus_source_url: "https://bbmp.karnataka.gov.in",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "BWSSB Bangalore Water Supply & Sewerage Board (AE / JE / Operator)",
    short_name: "BWSSB Recruitment",
    conducting_body: "BWSSB / KEA",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://bwssb.karnataka.gov.in",
    careers_url: "https://cetonline.karnataka.gov.in/kea",
    notification_url: "https://bwssb.karnataka.gov.in",
    results_url: "https://bwssb.karnataka.gov.in",
    admit_card_url: "https://cetonline.karnataka.gov.in/kea",
    syllabus_source_url: "https://bwssb.karnataka.gov.in",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "KEA Health Department Staff Nurse, Pharmacist & Lab Technician",
    short_name: "KEA Staff Nurse & Pharmacist",
    conducting_body: "Karnataka Examinations Authority",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://cetonline.karnataka.gov.in/kea",
    careers_url: "https://cetonline.karnataka.gov.in/kea/recruitment",
    notification_url: "https://cetonline.karnataka.gov.in/kea",
    results_url: "https://cetonline.karnataka.gov.in/kea",
    admit_card_url: "https://cetonline.karnataka.gov.in/kea",
    syllabus_source_url: "https://cetonline.karnataka.gov.in/kea",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "kea",
    active: 1
  },
  {
    name: "Karnataka Women & Child Development Anganwadi Worker & Helper",
    short_name: "Karnataka Anganwadi Worker/Helper",
    conducting_body: "Karnataka WCD Department",
    level: "state",
    state: "Karnataka",
    category: "Karnataka",
    official_site: "https://anganwadirecruit.kar.nic.in",
    careers_url: "https://anganwadirecruit.kar.nic.in",
    notification_url: "https://anganwadirecruit.kar.nic.in",
    results_url: "https://anganwadirecruit.kar.nic.in",
    admit_card_url: "https://anganwadirecruit.kar.nic.in",
    syllabus_source_url: "https://anganwadirecruit.kar.nic.in",
    frequency: "annual",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },

  // ==========================================
  // ALL-INDIA / CENTRAL - SMALL TO HIGH
  // ==========================================
  // India Post (Central Group C & D)
  {
    name: "India Post Gramin Dak Sevak (GDS - BPM, ABPM & Dak Sevak)",
    short_name: "India Post GDS",
    conducting_body: "Department of Posts (India Post)",
    level: "central",
    state: null,
    category: "Central",
    official_site: "https://indiapostgdsonline.gov.in",
    careers_url: "https://indiapostgdsonline.gov.in",
    notification_url: "https://indiapostgdsonline.gov.in",
    results_url: "https://indiapostgdsonline.gov.in",
    admit_card_url: "https://indiapostgdsonline.gov.in",
    syllabus_source_url: "https://indiapostgdsonline.gov.in",
    frequency: "annual",
    scrape_frequency: 30,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "India Post Postman, Mail Guard & Multi-Tasking Staff (MTS)",
    short_name: "India Post Postman & MTS",
    conducting_body: "Department of Posts (India Post)",
    level: "central",
    state: null,
    category: "Central",
    official_site: "https://www.indiapost.gov.in",
    careers_url: "https://www.indiapost.gov.in/VAS/Pages/Content/Recruitments.aspx",
    notification_url: "https://www.indiapost.gov.in",
    results_url: "https://www.indiapost.gov.in",
    admit_card_url: "https://www.indiapost.gov.in",
    syllabus_source_url: "https://www.indiapost.gov.in",
    frequency: "annual",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  // SSC (Central High to Low)
  {
    name: "SSC Junior Hindi Translator, Junior Translator and Senior Hindi Translator",
    short_name: "SSC JHT",
    conducting_body: "Staff Selection Commission",
    level: "central",
    state: null,
    category: "SSC",
    official_site: "https://ssc.gov.in",
    careers_url: "https://ssc.gov.in/candidate-portal",
    notification_url: "https://ssc.gov.in/notice-board",
    results_url: "https://ssc.gov.in/results",
    admit_card_url: "https://ssc.gov.in",
    syllabus_source_url: "https://ssc.gov.in",
    frequency: "annual",
    scrape_frequency: 30,
    adapter_type: "ssc",
    active: 1
  },
  // UPSC (Central High / Officers)
  {
    name: "UPSC Enforcement Officer / Accounts Officer & APFC (EPFO)",
    short_name: "UPSC EPFO EO/AO",
    conducting_body: "Union Public Service Commission",
    level: "central",
    state: null,
    category: "UPSC",
    official_site: "https://upsc.gov.in",
    careers_url: "https://upsconline.nic.in",
    notification_url: "https://upsc.gov.in/examinations/active-examinations",
    results_url: "https://upsc.gov.in/examinations/written-results",
    admit_card_url: "https://upsconline.nic.in/eadmitcard",
    syllabus_source_url: "https://upsc.gov.in",
    frequency: "irregular",
    scrape_frequency: 30,
    adapter_type: "upsc",
    active: 1
  },
  {
    name: "UPSC Indian Economic Service / Indian Statistical Service (IES / ISS)",
    short_name: "UPSC IES/ISS",
    conducting_body: "Union Public Service Commission",
    level: "central",
    state: null,
    category: "UPSC",
    official_site: "https://upsc.gov.in",
    careers_url: "https://upsconline.nic.in",
    notification_url: "https://upsc.gov.in/examinations/active-examinations",
    results_url: "https://upsc.gov.in/examinations/written-results",
    admit_card_url: "https://upsconline.nic.in/eadmitcard",
    syllabus_source_url: "https://upsc.gov.in",
    frequency: "annual",
    scrape_frequency: 30,
    adapter_type: "upsc",
    active: 1
  },
  // Intelligence Bureau & Paramilitary Forces (Small to High)
  {
    name: "Intelligence Bureau Assistant Central Intelligence Officer (IB ACIO Grade-II)",
    short_name: "IB ACIO",
    conducting_body: "Intelligence Bureau (Ministry of Home Affairs)",
    level: "central",
    state: null,
    category: "Defence",
    official_site: "https://www.mha.gov.in",
    careers_url: "https://www.mha.gov.in/en/notifications/vacancies",
    notification_url: "https://www.mha.gov.in",
    results_url: "https://www.mha.gov.in",
    admit_card_url: "https://www.mha.gov.in",
    syllabus_source_url: "https://www.mha.gov.in",
    frequency: "annual",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "Intelligence Bureau Security Assistant / Executive & MTS",
    short_name: "IB SA & MTS",
    conducting_body: "Intelligence Bureau (Ministry of Home Affairs)",
    level: "central",
    state: null,
    category: "Defence",
    official_site: "https://www.mha.gov.in",
    careers_url: "https://www.mha.gov.in/en/notifications/vacancies",
    notification_url: "https://www.mha.gov.in",
    results_url: "https://www.mha.gov.in",
    admit_card_url: "https://www.mha.gov.in",
    syllabus_source_url: "https://www.mha.gov.in",
    frequency: "annual",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "Indo-Tibetan Border Police Constable & Head Constable (Tradesmen / GD)",
    short_name: "ITBP Recruitment",
    conducting_body: "Indo-Tibetan Border Police (ITBP)",
    level: "central",
    state: null,
    category: "Defence",
    official_site: "https://itbpolice.nic.in",
    careers_url: "https://recruitment.itbpolice.nic.in",
    notification_url: "https://recruitment.itbpolice.nic.in",
    results_url: "https://recruitment.itbpolice.nic.in",
    admit_card_url: "https://recruitment.itbpolice.nic.in",
    syllabus_source_url: "https://itbpolice.nic.in",
    frequency: "annual",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "Sashastra Seema Bal Constable Tradesmen & Sub-Inspector",
    short_name: "SSB Recruitment",
    conducting_body: "Sashastra Seema Bal (SSB)",
    level: "central",
    state: null,
    category: "Defence",
    official_site: "https://ssb.gov.in",
    careers_url: "https://ssbrectt.gov.in",
    notification_url: "https://ssbrectt.gov.in",
    results_url: "https://ssbrectt.gov.in",
    admit_card_url: "https://ssbrectt.gov.in",
    syllabus_source_url: "https://ssb.gov.in",
    frequency: "annual",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "Assam Rifles Technical & Tradesmen Rally",
    short_name: "Assam Rifles Tradesmen",
    conducting_body: "Assam Rifles (MHA)",
    level: "central",
    state: null,
    category: "Defence",
    official_site: "https://www.assamrifles.gov.in",
    careers_url: "https://www.assamrifles.gov.in/onlineapp",
    notification_url: "https://www.assamrifles.gov.in",
    results_url: "https://www.assamrifles.gov.in",
    admit_card_url: "https://www.assamrifles.gov.in",
    syllabus_source_url: "https://www.assamrifles.gov.in",
    frequency: "annual",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "Indian Coast Guard Navik (General Duty / Domestic Branch) & Yantrik",
    short_name: "Coast Guard Navik/Yantrik",
    conducting_body: "Indian Coast Guard",
    level: "central",
    state: null,
    category: "Defence",
    official_site: "https://joinindiancoastguard.cdac.in",
    careers_url: "https://joinindiancoastguard.cdac.in",
    notification_url: "https://joinindiancoastguard.cdac.in",
    results_url: "https://joinindiancoastguard.cdac.in",
    admit_card_url: "https://joinindiancoastguard.cdac.in",
    syllabus_source_url: "https://joinindiancoastguard.cdac.in",
    frequency: "annual",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "Indian Navy Agniveer (SSR - Senior Secondary Recruit & MR - Matric Recruit)",
    short_name: "Navy Agniveer (SSR/MR)",
    conducting_body: "Indian Navy",
    level: "central",
    state: null,
    category: "Defence",
    official_site: "https://joinindiannavy.gov.in",
    careers_url: "https://www.joinindiannavy.gov.in",
    notification_url: "https://www.joinindiannavy.gov.in",
    results_url: "https://www.joinindiannavy.gov.in",
    admit_card_url: "https://www.joinindiannavy.gov.in",
    syllabus_source_url: "https://www.joinindiannavy.gov.in",
    frequency: "annual",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "Indian Air Force Agniveer Vayu (Intake 01/2026 & 02/2026)",
    short_name: "Air Force Agniveer Vayu",
    conducting_body: "Indian Air Force",
    level: "central",
    state: null,
    category: "Defence",
    official_site: "https://agnipathvayu.cdac.in",
    careers_url: "https://agnipathvayu.cdac.in/AV",
    notification_url: "https://agnipathvayu.cdac.in",
    results_url: "https://agnipathvayu.cdac.in",
    admit_card_url: "https://agnipathvayu.cdac.in",
    syllabus_source_url: "https://agnipathvayu.cdac.in",
    frequency: "annual",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  // Railways RRB (Small to High)
  {
    name: "RRB Technician Grade-I Signal & Grade-III",
    short_name: "RRB Technician",
    conducting_body: "Railway Recruitment Boards",
    level: "central",
    state: null,
    category: "Railway",
    official_site: "https://www.rrbapply.gov.in",
    careers_url: "https://www.rrbapply.gov.in",
    notification_url: "https://www.rrbapply.gov.in",
    results_url: "https://www.rrbapply.gov.in",
    admit_card_url: "https://www.rrbapply.gov.in",
    syllabus_source_url: "https://indianrailways.gov.in",
    frequency: "annual",
    scrape_frequency: 30,
    adapter_type: "rrb",
    active: 1
  },
  {
    name: "RRB Paramedical Staff (Staff Nurse, Lab Assistant, Pharmacist)",
    short_name: "RRB Paramedical",
    conducting_body: "Railway Recruitment Boards",
    level: "central",
    state: null,
    category: "Railway",
    official_site: "https://www.rrbapply.gov.in",
    careers_url: "https://www.rrbapply.gov.in",
    notification_url: "https://www.rrbapply.gov.in",
    results_url: "https://www.rrbapply.gov.in",
    admit_card_url: "https://www.rrbapply.gov.in",
    syllabus_source_url: "https://indianrailways.gov.in",
    frequency: "irregular",
    scrape_frequency: 30,
    adapter_type: "rrb",
    active: 1
  },
  // Financial, Regulators & Insurance (Central High to Low)
  {
    name: "Securities and Exchange Board of India Assistant Manager (SEBI Grade A)",
    short_name: "SEBI Grade A",
    conducting_body: "Securities and Exchange Board of India",
    level: "central",
    state: null,
    category: "Banking",
    official_site: "https://www.sebi.gov.in",
    careers_url: "https://www.sebi.gov.in/department/human-resources-department-37/career-37.html",
    notification_url: "https://www.sebi.gov.in",
    results_url: "https://www.sebi.gov.in",
    admit_card_url: "https://ibpsonline.ibps.in",
    syllabus_source_url: "https://www.sebi.gov.in",
    frequency: "annual",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "Pension Fund Regulatory and Development Authority Assistant Manager (PFRDA Grade A)",
    short_name: "PFRDA Grade A",
    conducting_body: "Pension Fund Regulatory and Development Authority",
    level: "central",
    state: null,
    category: "Banking",
    official_site: "https://www.pfrda.org.in",
    careers_url: "https://www.pfrda.org.in/index1.cshtml?lsid=81",
    notification_url: "https://www.pfrda.org.in",
    results_url: "https://www.pfrda.org.in",
    admit_card_url: "https://ibpsonline.ibps.in",
    syllabus_source_url: "https://www.pfrda.org.in",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "Export-Import Bank of India Management Trainee (EXIM Bank MT)",
    short_name: "EXIM Bank MT",
    conducting_body: "Export-Import Bank of India",
    level: "central",
    state: null,
    category: "Banking",
    official_site: "https://www.eximbankindia.in",
    careers_url: "https://www.eximbankindia.in/careers",
    notification_url: "https://www.eximbankindia.in",
    results_url: "https://www.eximbankindia.in",
    admit_card_url: "https://ibpsonline.ibps.in",
    syllabus_source_url: "https://www.eximbankindia.in",
    frequency: "annual",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "ECGC Limited Probationary Officer (ECGC PO)",
    short_name: "ECGC PO",
    conducting_body: "Export Credit Guarantee Corporation of India",
    level: "central",
    state: null,
    category: "Banking",
    official_site: "https://www.ecgc.in",
    careers_url: "https://www.ecgc.in/career",
    notification_url: "https://www.ecgc.in",
    results_url: "https://www.ecgc.in",
    admit_card_url: "https://ibpsonline.ibps.in",
    syllabus_source_url: "https://www.ecgc.in",
    frequency: "annual",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "Life Insurance Corporation Assistant (LIC Assistant Clerical Cadre)",
    short_name: "LIC Assistant",
    conducting_body: "Life Insurance Corporation of India",
    level: "central",
    state: null,
    category: "Banking",
    official_site: "https://licindia.in",
    careers_url: "https://licindia.in/Bottom-Links/careers",
    notification_url: "https://licindia.in",
    results_url: "https://licindia.in",
    admit_card_url: "https://ibpsonline.ibps.in",
    syllabus_source_url: "https://licindia.in",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "United India Insurance Company Administrative Officer (UIIC AO)",
    short_name: "UIIC AO",
    conducting_body: "United India Insurance Company Limited",
    level: "central",
    state: null,
    category: "Banking",
    official_site: "https://uiic.co.in",
    careers_url: "https://uiic.co.in/careers",
    notification_url: "https://uiic.co.in",
    results_url: "https://uiic.co.in",
    admit_card_url: "https://uiic.co.in",
    syllabus_source_url: "https://uiic.co.in",
    frequency: "annual",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "Oriental Insurance Company Limited Administrative Officer (OICL AO)",
    short_name: "OICL AO",
    conducting_body: "Oriental Insurance Company Limited",
    level: "central",
    state: null,
    category: "Banking",
    official_site: "https://orientalinsurance.org.in",
    careers_url: "https://orientalinsurance.org.in/careers",
    notification_url: "https://orientalinsurance.org.in",
    results_url: "https://orientalinsurance.org.in",
    admit_card_url: "https://orientalinsurance.org.in",
    syllabus_source_url: "https://orientalinsurance.org.in",
    frequency: "annual",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "National Insurance Company Limited Administrative Officer (NICL AO)",
    short_name: "NICL AO",
    conducting_body: "National Insurance Company Limited",
    level: "central",
    state: null,
    category: "Banking",
    official_site: "https://nationalinsurance.nic.co.in",
    careers_url: "https://nationalinsurance.nic.co.in/en/recruitment",
    notification_url: "https://nationalinsurance.nic.co.in",
    results_url: "https://nationalinsurance.nic.co.in",
    admit_card_url: "https://nationalinsurance.nic.co.in",
    syllabus_source_url: "https://nationalinsurance.nic.co.in",
    frequency: "annual",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  // Teaching, Medical & Social Security (Central High to Low)
  {
    name: "Central Teacher Eligibility Test (CTET Paper 1 & Paper 2)",
    short_name: "CTET",
    conducting_body: "Central Board of Secondary Education (CBSE)",
    level: "central",
    state: null,
    category: "Central",
    official_site: "https://ctet.nic.in",
    careers_url: "https://ctet.nic.in",
    notification_url: "https://ctet.nic.in",
    results_url: "https://ctet.nic.in",
    admit_card_url: "https://ctet.nic.in",
    syllabus_source_url: "https://ctet.nic.in",
    frequency: "annual",
    scrape_frequency: 30,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "Kendriya Vidyalaya Sangathan Teachers (KVS PRT, TGT, PGT)",
    short_name: "KVS Recruitment",
    conducting_body: "Kendriya Vidyalaya Sangathan",
    level: "central",
    state: null,
    category: "Central",
    official_site: "https://kvsangathan.nic.in",
    careers_url: "https://kvsangathan.nic.in/employment-notice",
    notification_url: "https://kvsangathan.nic.in",
    results_url: "https://kvsangathan.nic.in",
    admit_card_url: "https://kvsangathan.nic.in",
    syllabus_source_url: "https://kvsangathan.nic.in",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "Navodaya Vidyalaya Samiti Teachers (NVS TGT, PGT & Non-Teaching)",
    short_name: "NVS Recruitment",
    conducting_body: "Navodaya Vidyalaya Samiti",
    level: "central",
    state: null,
    category: "Central",
    official_site: "https://navodaya.gov.in",
    careers_url: "https://navodaya.gov.in/nvs/en/recruitment/Notification-Vacancies",
    notification_url: "https://navodaya.gov.in",
    results_url: "https://navodaya.gov.in",
    admit_card_url: "https://navodaya.gov.in",
    syllabus_source_url: "https://navodaya.gov.in",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "NTA UGC National Eligibility Test (UGC NET / JRF)",
    short_name: "UGC NET",
    conducting_body: "National Testing Agency (NTA)",
    level: "central",
    state: null,
    category: "Central",
    official_site: "https://ugcnet.nta.ac.in",
    careers_url: "https://ugcnet.nta.ac.in",
    notification_url: "https://ugcnet.nta.ac.in",
    results_url: "https://ugcnet.nta.ac.in",
    admit_card_url: "https://ugcnet.nta.ac.in",
    syllabus_source_url: "https://ugcnetonline.in",
    frequency: "annual",
    scrape_frequency: 30,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "AIIMS Nursing Officer Recruitment Common Eligibility Test (NORCET)",
    short_name: "AIIMS NORCET",
    conducting_body: "All India Institute of Medical Sciences",
    level: "central",
    state: null,
    category: "Central",
    official_site: "https://aiimsexams.ac.in",
    careers_url: "https://aiimsexams.ac.in",
    notification_url: "https://aiimsexams.ac.in",
    results_url: "https://aiimsexams.ac.in",
    admit_card_url: "https://aiimsexams.ac.in",
    syllabus_source_url: "https://aiimsexams.ac.in",
    frequency: "annual",
    scrape_frequency: 30,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "Employees State Insurance Corporation Upper Division Clerk & MTS (ESIC UDC/MTS)",
    short_name: "ESIC UDC & MTS",
    conducting_body: "Employees' State Insurance Corporation",
    level: "central",
    state: null,
    category: "Central",
    official_site: "https://www.esic.gov.in",
    careers_url: "https://www.esic.gov.in/recruitments",
    notification_url: "https://www.esic.gov.in/recruitments",
    results_url: "https://www.esic.gov.in/recruitments",
    admit_card_url: "https://www.esic.gov.in",
    syllabus_source_url: "https://www.esic.gov.in",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "Food Corporation of India Assistant Grade-III (FCI AG-3 General, Depot, Accounts, Technical)",
    short_name: "FCI Assistant Grade-III",
    conducting_body: "Food Corporation of India",
    level: "central",
    state: null,
    category: "Central",
    official_site: "https://fci.gov.in",
    careers_url: "https://fci.gov.in/current-recruitment.php",
    notification_url: "https://fci.gov.in/current-recruitment.php",
    results_url: "https://fci.gov.in",
    admit_card_url: "https://fci.gov.in",
    syllabus_source_url: "https://fci.gov.in",
    frequency: "irregular",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "Security Printing & Minting Corporation of India (SPMCIL Junior Technician & Attendant)",
    short_name: "SPMCIL Recruitment",
    conducting_body: "SPMCIL (Ministry of Finance)",
    level: "central",
    state: null,
    category: "PSU",
    official_site: "https://www.spmcil.com",
    careers_url: "https://www.spmcil.com/en/careers",
    notification_url: "https://www.spmcil.com",
    results_url: "https://www.spmcil.com",
    admit_card_url: "https://www.spmcil.com",
    syllabus_source_url: "https://www.spmcil.com",
    frequency: "annual",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  },
  {
    name: "Ordnance Factory Board Trade Apprentices (Non-ITI & Ex-ITI)",
    short_name: "OFB Apprentices",
    conducting_body: "Yantra India Limited / Ordnance Factory Board",
    level: "central",
    state: null,
    category: "Central",
    official_site: "https://ddpdoo.gov.in",
    careers_url: "https://ddpdoo.gov.in",
    notification_url: "https://ddpdoo.gov.in",
    results_url: "https://ddpdoo.gov.in",
    admit_card_url: "https://ddpdoo.gov.in",
    syllabus_source_url: "https://ddpdoo.gov.in",
    frequency: "annual",
    scrape_frequency: 360,
    adapter_type: "generic",
    active: 1
  }
];

let addedCount = 0;
for (const ex of newExams) {
  const key = (ex.short_name || ex.name).toLowerCase().trim();
  if (!existingNames.has(key)) {
    existingRegistry.push(ex);
    existingNames.add(key);
    addedCount++;
  }
}

fs.writeFileSync(registryPath, JSON.stringify(existingRegistry, null, 2), 'utf8');
console.log(`✓ Added ${addedCount} new exams! Total exams in registry: ${existingRegistry.length}`);
